version: "2"

linters:
  enable:
    - asasalint # checks for pass []any as any in variadic func(...any)
    - asciicheck # checks that your code does not contain non-ASCII identifiers
    - bidichk # checks for dangerous unicode character sequences
    - bodyclose # checks whether HTTP response body is closed successfully
    - canonicalheader # checks whether net/http.Header uses canonical header
    - containedctx # detects struct contained context.Context field
    - contextcheck # checks the function whether use a non-inherited context
    - copyloopvar # detects places where loop variables are copied
    - cyclop # checks function and package cyclomatic complexity
    - dogsled # checks assignments with too many blank identifiers (e.g. x, _, _, _, := f())
    - dupl # detects duplicate fragments of code
    - dupword # checks for duplicate words in the source code
    - durationcheck # checks for two durations multiplied together
    - embeddedstructfieldcheck # checks embedded types in structs
    - errcheck # checking for unchecked errors
    - errname # checks that sentinel errors are prefixed with the Err and error types are suffixed with the Error
    - errorlint # finds code that will cause problems with the error wrapping scheme introduced in Go 1.13
    - exhaustive # checks exhaustiveness of enum switch statements
    - exhaustruct # checks if all structure fields are initialized
    - exptostd # detects functions from golang.org/x/exp/ that can be replaced by std functions
    - fatcontext # detects nested contexts in loops
    - forbidigo # forbids identifiers (Print functions by default)
  
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    
    copyloopvar:
      check-alias: true

    embeddedstructfieldcheck:
      forbid-mutex: true

    exhaustive:
      check:
        - switch
        - map

    exhaustruct:
      exclude:
        - ^net/http.Response$
        - ^net/http.Server$
        - ^github.com/marchuknikolay/rss-parser/internal/model.Channel$
        - ^github.com/marchuknikolay/rss-parser/internal/storage.Storage$

  exclusions:
    rules:
      - path: '_test\.go'
        linters:
          - dupl
          - exhaustruct