version: "2"

linters:
  enable:
    - asasalint # checks for pass []any as any in variadic func(...any)
    - asciicheck # checks that your code does not contain non-ASCII identifiers
    - bidichk # checks for dangerous unicode character sequences
    - bodyclose # checks whether HTTP response body is closed successfully
    - canonicalheader # checks whether net/http.Header uses canonical header
    - containedctx # detects struct contained context.Context field
    - errcheck # checking for unchecked errors
  
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true