services:

  app:
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: [ "/app/start.sh" ]
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  db:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME" ]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
