services:

  app:
    build: .
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=rss_feed
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
