services:

  app:
    build: .
    depends_on:
      - db

  db:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
